name: Updater Comment

on:
  pull_request:
    types:
      - opened

jobs:
  updater-comment:
    name: Comment updater settings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log("Context")
            console.log(context)
            console.log("\n\nIssue Object")
            console.log(context.issue)
            console.log("\n\nRepo Object")
            console.log(context.repo)
            const channel = "nightly"
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `TODO`,
            })
